
name: Sync GitHub to Gitee

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [closed] # 监听 PR 关闭事件
  workflow_dispatch:

env:
  GITHUB_OWNER: 2c2a
  GITEE_OWNER: Bilibili-Supercmd
  GIT_USER_NAME: BiliBili UP主Supercmd
  GIT_USER_EMAIL: trustedinster@outlook.com

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    # 关键判断：如果是 PR 触发，必须满足 merged 为 true；如果是 push 或手动触发则正常执行
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 设置 Git 用户信息
      - name: Configure Git
        run: |
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"

      # 3. 同步代码到 Gitee
      - name: Mirror GitHub to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ env.GITHUB_OWNER }}
          dst: gitee/${{ env.GITEE_OWNER }}
          dst_key: ${{ secrets.RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          static_list: "plugin-registry"
